Created Load balancer
agoel2411/terraform-in-21-days pull request #12
Opened 2023-07-29 09:01 UTC by agoel2411

2023-07-29 10:33 UTC, geoffrey1330 requested changes

2023-07-29 10:33 UTC, geoffrey1330 commented on level2/load_balancer.tf
> +}
could you please, add a newline at the end of file.

2023-07-29 10:33 UTC, geoffrey1330 commented on level2/instance.tf
> +
too much line space. could you please reduce it to one

2023-08-02 06:38 UTC, agoel2411 commented on level2/load_balancer.tf
> +}
done

2023-08-02 06:38 UTC, agoel2411 commented on level2/instance.tf
> +
done

2023-08-02 08:58 UTC, geoffrey1330 approved these changes

2023-08-02 14:58 UTC, merged